### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by azhang** [maticnetwork/eth-dagger.js#2] opened 2018-03-21 07:47 UTC
```
var Dagger = require('eth-dagger')
new Dagger(...)
```
doesn't work for me, I have to use
```
var Dagger = require('eth-dagger').default
new Dagger(...)
```

Also, is the mainnet supposed to be down currently?

**Comment by azhang** [comment] 2018-03-21 07:54
Ah I see, https://github.com/maticnetwork/eth-dagger-examples/blob/master/examples/multisig-wallet.js has updated example :)

**Comment by anurag-arjun** [comment] 2018-06-07 06:06
We will fix this as soon as possible. Also, mainnet is working now. Please check again.

**Comment by jdkanani** [comment] 2018-06-07 08:18
@azhang Fixed in newer version 0.0.1. I'm closing the issue for now. You can reopen it if it's not working as intended.

**Closed by jdkanani** 2018-06-07 08:18 UTC
